name: Build project
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            make
            patch
            git
            zip
            unzip
          pacboy: >-
            cmake:p
            gcc:p
            hidapi:p
            freetype:p
            libpng:p
            SDL2:p
            SDL2_net:p
            qt6:p
            7zip:p

      - name: Run build script
        run: msys2 -c 'export SIMPLE64_AUTOUPDATE=1; export NETPLAY_AUTH_CODE=${{ secrets.NETPLAY_AUTH_CODE }}; ./build.sh zip'
      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: simple64-win64
          path: simple64-*.zip
